export { calculate_brzycki_1rm } from "./methods/Brzycki";
export declare const calculateEpley1RM: () => void;
export declare const calculateLombardi1RM: () => void;
export declare const calculateOConor1RM: () => void;
export declare const calculateLander1RM: () => void;
export declare const calculateWathan1RM: () => void;
export declare const calculateMayhewSzekely1RM: () => void;
export declare const calculateFeigenbaum1RM: () => void;
export declare const calculatePrilepin1RM: () => void;
export declare const calculateLombardiII1RM: () => void;
export declare const calculateLyleMcDonald1RM: () => void;
export declare const calculateZatsiorsky1RM: () => void;
export declare const calculateSchwarzenegger1RM: () => void;
export declare const calculateEvanLand1RM: () => void;
export declare const calculateZechs1RM: () => void;
export declare const calculateAlanAragon1RM: () => void;
