export {calculate_epley_1rm} from "./methods/Epley"
export {calculate_brzycki_1rm} from "./methods/Brzycki"
export {calculate_adams_1rm} from "./methods/Adams"
export {calculate_baechle_1rm} from "./methods/Baechle"
export {calculate_berger_1rm} from "./methods/Berger"
export {calculate_brown_1rm} from "./methods/Brown"
export {calculate_kemmler_1rm} from "./methods/Kemmler"
export {calculate_lander_1rm} from "./methods/Lander"
export {calculate_lombardi_1rm} from "./methods/Lombardi"
export {calculate_mayhew_szekely_1rm} from "./methods/MayhewSzekely"
export {calculate_naclerio_1rm} from "./methods/Naclerio"
// OConner
export {calculate_wathan_1rm} from "./methods/Wathan"
